# Generated by Django 5.2.3 on 2025-07-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('junior-secondary', 'Junior Secondary'), ('upper-primary', 'Upper Primary'), ('lower-primary', 'Lower Primary')], max_length=20, unique=True)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
